---
- name: Set GPG APT key
  apt_key:
    url: "http://packages.microsoft.com/keys/microsoft.asc"
    state: present

- name: Add repository
  copy:
    content: "deb [arch=amd64] http://packages.microsoft.com/repos/vscode stable main"
    dest: /etc/apt/sources.list.d/terraform.list
    group: root
    owner: root
    mode: '0644'

- name: Install package
  apt:
    name: code
    update_cache: true
