---
- name: Set GPG APT key
  apt_key:
    url: "https://apt.releases.hashicorp.com/gpg"
    state: present

- name: Add repository
  copy:
    content: "deb [arch=amd64] https://apt.releases.hashicorp.com bullseye main"
    dest: /etc/apt/sources.list.d/terraform.list
    group: root
    owner: root
    mode: '0644'

- name: Install package
  apt:
    name: terraform
    update_cache: true
