---
- name: Set GPG APT key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian bullseye stable"
    state: present
    update_cache: true

- name: Install packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io
- name: Add user to docker group
  user: name="{{ lookup('env','USER') }}"
        groups=docker
        append=yes